FROM node:18

WORKDIR /app

# Dependencias del sistema y Oracle Instant Client
RUN apt-get update && apt-get install -y \
    wget unzip libaio1 libnsl2 build-essential python3 ca-certificates \
 && rm -rf /var/lib/apt/lists/* \
 && wget --no-cookies --no-check-certificate \
      --header "Cookie: oraclelicense=accept-securebackup-cookie" \
      https://download.oracle.com/otn_software/linux/instantclient/2113000/instantclient-basic-linux.x64-21.13.0.0.0dbru.zip \
 && unzip instantclient-basic-linux.x64-21.13.0.0.0dbru.zip -d /opt/oracle \
 && rm instantclient-basic-linux.x64-21.13.0.0.0dbru.zip \
 && ln -s /opt/oracle/instantclient_21_13 /opt/oracle/instantclient \
 && ln -s /opt/oracle/instantclient/libclntsh.so /opt/oracle/libclntsh.so \
 && echo "/opt/oracle/instantclient" > /etc/ld.so.conf.d/oracle-instantclient.conf \
 && ldconfig

# Variables de entorno
ENV LD_LIBRARY_PATH=/opt/oracle/instantclient
ENV PATH=$PATH:/opt/oracle/instantclient

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias y recompilar oracledb
RUN npm install --build-from-source --omit=dev

# Copiar el resto del proyecto
COPY . .

EXPOSE 3000

CMD ["node", "index.js"]
