const oracledb = require('oracledb');

const insertarRegistroCuadratura = async (connection, registro, nombreArchivo) => {
  await connection.execute(
    `INSERT INTO CUADRATURA_FILE_TBK (
      ID, DKTT_DT_REG, DKTT_DT_TYP, DKTT_DT_TC, DKTT_DT_SEQ_NUM, DKTT_DT_TRAN_DAT,
      DKTT_DT_TRAN_TIM, DKTT_DT_INST_RETAILER, DKTT_DT_ID_RETAILER, DKTT_DT_NAME_RETAILER,
      DKTT_DT_CARD, DKTT_DT_AMT_1, DKTT_DT_AMT_PROPINA, DKTT_TIPO_CUOTA,
      DKTT_DT_CANTI_CUOTAS, DKTT_DT_RESP_CDE, DKTT_DT_APPRV_CDE, DKTT_DT_TERM_NAME,
      DKTT_DT_ID_CAJA, DKTT_DT_NUM_BOLETA, DKTT_DT_AUTH_TRACK2, DKTT_DT_FECHA_VENTA,
      DKTT_DT_HORA_VENTA, DKTT_DT_FECHA_PAGO, DKTT_DT_COD_RECHAZO, DKTT_DT_GLOSA_RECHAZO,
      DKTT_DT_VAL_CUOTA, DKTT_DT_VAL_TASA, DKTT_DT_NUMERO_UNICO, DKTT_DT_TIPO_MONEDA,
      DKTT_DT_ID_RETAILER_RE, DKTT_DT_COD_SERVICIO, DKTT_DT_VCI, DKTT_MES_GRACIA,
      DKTT_PERIODO_GRACIA, STATUS_SAP_REGISTER, STATUS_SAP_DATE, FILE_NAME, DATE_LOAD_BBDD
    ) VALUES (
      :ID, :DKTT_DT_REG, :DKTT_DT_TYP, :DKTT_DT_TC, :DKTT_DT_SEQ_NUM, :DKTT_DT_TRAN_DAT,
      :DKTT_DT_TRAN_TIM, :DKTT_DT_INST_RETAILER, :DKTT_DT_ID_RETAILER, :DKTT_DT_NAME_RETAILER,
      :DKTT_DT_CARD, :DKTT_DT_AMT_1, :DKTT_DT_AMT_PROPINA, :DKTT_TIPO_CUOTA,
      :DKTT_DT_CANTI_CUOTAS, :DKTT_DT_RESP_CDE, :DKTT_DT_APPRV_CDE, :DKTT_DT_TERM_NAME,
      :DKTT_DT_ID_CAJA, :DKTT_DT_NUM_BOLETA, :DKTT_DT_AUTH_TRACK2, :DKTT_DT_FECHA_VENTA,
      :DKTT_DT_HORA_VENTA, :DKTT_DT_FECHA_PAGO, :DKTT_DT_COD_RECHAZO, :DKTT_DT_GLOSA_RECHAZO,
      :DKTT_DT_VAL_CUOTA, :DKTT_DT_VAL_TASA, :DKTT_DT_NUMERO_UNICO, :DKTT_DT_TIPO_MONEDA,
      :DKTT_DT_ID_RETAILER_RE, :DKTT_DT_COD_SERVICIO, :DKTT_DT_VCI, :DKTT_MES_GRACIA,
      :DKTT_PERIODO_GRACIA, '0', SYSDATE, :FILE_NAME, SYSDATE
    )`,
    { ...registro, FILE_NAME: nombreArchivo },
    { autoCommit: false }
  );
};

module.exports = {
  insertarRegistroCuadratura,
};
